### ISSUE TITLE
CMake Error: No download info given for 'oneapi_prog' and its source directory

### ISSUE THREAD

**Issue by pravin25** [ftyghome/ROS-oneAPI#1]
followed build instruction, but unable to build.

environment information:
1) Ubuntu 20.04
2) ros-noetic

**Comment by ftyghome** [comment]
I am not able to reproduce this issue so far, but I guess you can try the following step to solve it.
Use git to clone this repository and change the name of root folder from ROS-oneAPI to ros_oneapi, then try again to see if this problem disappeared.

**Comment by pravin25** [comment]
now able to run, after changing name root folder from ROS-oneAPI to ros_oneapi.
Thank you.
